// Generated by swift-plugin-generator 0.1.0
import Foundation
import PackagePlugin

@main
struct SubtreePlugin: CommandPlugin {
    func performCommand(context: PluginContext, arguments: [String]) async throws {
        let tool = try context.tool(named: "subtree")
        let toolURL = tool.url
        
        let process = Process()
        process.executableURL = toolURL
        process.arguments = arguments
        
        try process.run()
        process.waitUntilExit()
        
        if process.terminationStatus != 0 {
            Diagnostics.error("subtree exited with code \(process.terminationStatus)")
        }
    }
}
