# Generated by swift-plugin-generator 0.1.0
# Dockerfile enables Linux validation of generated plugin via `docker build .`

FROM swift:latest

WORKDIR /package

COPY . .

RUN swift build
RUN swift test
RUN swift package plugin subtree --help

CMD ["swift", "run", "subtree", "--version"]
