// swift-tools-version: 6.0
// Generated by swift-plugin-generator 0.1.0

import PackageDescription

let package = Package(
    name: "swift-plugin-subtree",
    platforms: [.macOS(.v13)],
    products: [
        .executable(name: "subtree", targets: ["SubtreeExecutable"]),
        .plugin(name: "SubtreePlugin", targets: ["SubtreePlugin"])
    ],
    dependencies: [
        .package(url: "https://github.com/21-DOT-DEV/swift-artifact-parser", exact: "0.0.1")
    ],
    targets: [
        // Executable target - wraps binary using ArtifactParser
        .executableTarget(
            name: "SubtreeExecutable",
            dependencies: [
                .product(name: "ArtifactParser", package: "swift-artifact-parser")
            ]
        ),
        
        // Plugin target - command plugin
        .plugin(
            name: "SubtreePlugin",
            capability: .command(
                intent: .custom(verb: "subtree", description: ""),
                permissions: [.writeToPackageDirectory(reason: "subtree may write output files")]
            ),
            dependencies: ["subtree"]
        ),
        
        // Binary target - references artifact bundle

        .binaryTarget(
            name: "subtree",
            url: "https://github.com/21-DOT-DEV/subtree/releases/download/0.0.9/subtree.artifactbundle.zip",
            checksum: "3d4e04773636646af6aa95293f1f8b5c811c2b9daf4a49b0ad349299c4e7b6b6"
        ),


    ]
)
