// Generated by swift-plugin-generator 0.1.0
import Foundation
import ArtifactParser

@main
struct SubtreeWrapper {
    static func main() async throws {
        guard let binaryPath = ArtifactParser.getPathToBinary(
            binaryName: "subtree",
            repositoryName: "swift-plugin-subtree"
        ) else {
            print("Error: Unable to find subtree binary in artifact bundle")
            exit(1)
        }
        
        let process = Process()
        process.executableURL = URL(fileURLWithPath: binaryPath)
        process.arguments = Array(CommandLine.arguments.dropFirst())
        
        try process.run()
        process.waitUntilExit()
        
        exit(process.terminationStatus)
    }
}
